name: PHP Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in working directory
        run: ls -la ${{ github.workspace }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install Composer dependencies
        run: composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader
        working-directory: ${{ github.workspace }}

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
        working-directory: ${{ github.workspace }}
